config/routes.rb
OnlineTimesheets::Application.routes.draw do
  
  root to: 'sessions#new'

  resources :timesheets do
    resources :entries
  end

  resources :users, only: [:new, :create]

  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"
  post "gone" => "timesheets#update_gone", as: "gone"

end

app/models/daylist.rb
class Daylist

  attr_reader :entries

  def initialize(entries)
    @entries = entries.sort_by { |entry| entry.come}
  end

  def calc_break
    difference = 0

    @entries.each.with_index do |entry, i|
      if(entry.gone && entry.come)
        difference += @entries[i+1].come - @entries[i].gone unless entry == @entries.last    
      end
    end

    secs_to_hours difference
  end

  def secs_to_hours (diff)
    hours = diff / 3600
    hours.round(2)
  end

  def spend_time
    secs = 0
    @entries.each do |entry| 
      if(entry.gone && entry.come)
        secs += entry.gone - entry.come
      end
    end
    secs_to_hours secs
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :come, :day, :gone, :timesheet_id
  belongs_to :timesheets

  def complete?
    come.present? && gone.present?
  end

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  attr_accessible :month, :year, :user_id
  belongs_to :user
  has_many :entries, :dependent => :destroy

  def daylist_for_date(date)
    entries_for_date = entries.select { |entry| entry.day == date}
    daylist = Daylist.new(entries_for_date)
  end

  def entry_addable?
    entries.all?(&:complete?)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :firstname, :lastname, :password, :password_confirmation
  has_many :timesheets

  validates :firstname, :lastname, presence: true

  def fullname
    @fullname = firstname + " " + lastname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    #else
    #  redirect_to login_path
    end
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def update
    @entry = Entry.find(params[:id])
    now = Time.zone.now.utc
    @entry.gone=  now

    if @entry.save
      flash[:notice] = 'Erfolgreich gespeichert'
    else
      flash[:alert] = 'Konnte nicht gespeichert werden'
    end

    timesheet = Timesheet.find(params[:timesheet_id])
    
    redirect_to timesheet_path(timesheet)
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    timesheet = Timesheet.find(params[:timesheet_id])
    
    redirect_to timesheet_path(timesheet), notice: "Der Eintrag wurde gelöscht."
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create  
    user = User.find_by_lastname(params[:lastname])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to timesheets_path,
      notice: "Erfolgreiches Log in."
    else
      flash.now.alert = "Fehlerhafter Name oder Passwort."
      render "new"
    end
  end

  def destroy   
    session[:user_id] = nil
    redirect_to root_path,
    notice: "Sie haben sich ausgeloggt."
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_filter :require_login

  def new
    date = Date.today
    @timesheet = current_user.timesheets.build(:month => date.month, :year => date.year)
    if @timesheet.save
      redirect_to timesheets_path, notice: "Ein neuer Stundenzettel wurde erstellt."
    end
  end

  def index
    @timesheets = current_user.timesheets
  end

  def show
    @timesheet = current_user.timesheets.find(params[:id])
    @entries = @timesheet.entries
  end

  def destroy
    @timesheet = current_user.timesheets.find(params[:id])
    @timesheet.destroy
    redirect_to timesheets_url, notice: "Der Stundenzettel wurde gelöscht."
  end


  def require_login
    unless user_signed_in?
      redirect_to login_path,
      notice: "Bitte loggen Sie sich ein."
    end
  end

  def update
    @timesheet = current_user.timesheets.find(params[:id])
    now = Time.zone.now.utc
    @entry = @timesheet.entries.create(:day => now.to_date, :come => now)
    redirect_to timesheet_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to login_path,
      notice: "Benutzer erfolgreich angelegt."
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper

  def number_to_word(month)
     Date::MONTHNAMES[month]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      OnlineTimesheets - #{@title || "Unbenannt"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #container
      #header
        %h1 Meine Stundenzettel
      #content
        - if flash[:notice]
          %p{:class => "alert alert-success"}
            = flash[:notice]
        - if flash[:alert]
          %p{:class => "alert"}
            = flash[:alert]
        = yield
      #footer
        - if user_signed_in?
          = link_to t("links.logout"), logout_path, method: :delete
        - else
          = link_to t("links.login"), login_path

app/views/timesheets/_entry.haml
%tr
  %td
    = entry.day
  %td
    - if entry.come
      = entry.come.to_formatted_s(:short)
  %td
    - if entry.gone
      = entry.gone.to_formatted_s(:short)
  %td   
    = timesheet.daylist_for_date(entry.day).calc_break
  %td
    = timesheet.daylist_for_date(entry.day).spend_time
  %td
    - if !entry.gone
      = form_for [timesheet, entry] do |f|
        = f.submit "Gegangen", :class => 'btn btn-small'
    - else
      = link_to "Löschen", timesheet_entry_path(timesheet,entry), :confirm => "Wollen Sie diesen Eintrag wirklich löschen?", :method => :delete

app/views/timesheets/_timesheet.haml
%li{ :class => 'nav divider' }
  = (link_to number_to_word(timesheet.month)+" #{timesheet.year}", timesheet_path(timesheet)) + " ("
  = (link_to "Löschen", timesheet, :confirm => "Wollen Sie diesen Stundenzettel wirklich löschen?", :method => :delete) + ")"

app/views/timesheets/index.haml
- @title = "Meine Stundenzettel"
%h2 Stundenzettel
%ul
  = render :partial => "timesheet", :collection => @timesheets
%p
  = link_to "Neuer Stundenzettel", new_timesheet_path, :class => 'btn'

app/views/timesheets/new.haml
%h2 Neuen Stundenzettel anlegen
= form_for(@timesheet) do |f|
  - if @timesheet.user.errors.any?
    %ul
      - @timesheet.user.errors.full_messages.each do |msg|
        %li= msg
  %p
    = f.label :month, "Monat"
    = f.text_field :month
  %p= f.submit "anlegen"

app/views/timesheets/show.haml
- @title = "Stundenzettel"
%h2
  Monat:
  = number_to_word(@timesheet.month)+" #{@timesheet.year}"
%h3
  Name:
  = @current_user.fullname
%table{ :class => 'table table-hover' }
  %tr
    %th Tag
    %th gekommen
    %th gegangen
    %th Pause
    %th Stunden
  = render :partial => "entry", :collection => @entries, :locals => { :timesheet => @timesheet }

= form_for(@timesheet) do |f|
  = f.submit "Gekommen", :disabled => !@timesheet.entry_addable?, :class=> 'btn btn-primary'
= link_to "Zurück", timesheets_path

app/views/users/new.haml
- @title = "Neuer Benutzer"
%h2 Neuen Benutzer anlegen
= form_for(@user) do |f|
  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg
  %p
    = f.label :firstname, "Vorname"
    = f.text_field :firstname
  %p
    = f.label :lastname, "Nachname"
    = f.text_field :lastname
  %p
    = f.label :password, "Passwort"
    = f.password_field :password
  %p
    = f.label :password_confirmation, "Passwortbestätigung"
    = f.password_field :password_confirmation
  %p= f.submit "Anlegen"